export const boyNames = [
    "Alonso", "Andrés", "Antonio", "Armando", "Arturo", "Benjamín", "Bruno", "Carlos", "César",
    "Cristian", "Daniel", "David", "Diego", "Eduardo", "Emilio", "Enrique", "Esteban", "Eugenio", "Felipe",
    "Fernando", "Francisco", "Gabriel", "Gerardo", "Gonzalo", "Guillermo", "Héctor", "Hugo", "Ignacio", "Isaac",
    "Iván", "Javier", "Jesús", "Joaquín", "Joel", "Jonás", "Jorge", "José", "José Luis", "Juan",
    "Juan Carlos", "Juan José", "Julián", "Julio", "Kevin", "Lautaro", "Leonardo", "Luis", "Manuel", "Marcelo",
    "Marcos", "Mario", "Martín", "Mateo", "Matías", "Mauricio", "Maximiliano", "Miguel", "Miguel Ángel", "Nicolás",
    "Óscar", "Pablo", "Pedro", "Rafael", "Ramiro", "Raúl", "Ricardo", "Rodrigo", "Rubén", "Salvador",
    "Samuel", "Santiago", "Sebastián", "Sergio", "Simón", "Tomás", "Ulises", "Valentín", "Vicente", "Víctor",
    "Adrián", "Álvaro", "Bautista", "Camilo", "Damián", "Elías", "Ernesto", "Fabián", "Fausto", "Gaspar",
    "Guido", "Iker", "Ismael", "Jaime", "Leandro", "Lisandro", "Luciano", "Nahuel", "Thiago", "Abel",
    "Abraham", "Agustín", "Aitor", "Alan", "Alberto", "Aldo", "", "Alex", "Alexis", "Alfredo",
    "Amador", "Américo", "Aníbal", "Anselmo", "Arnaldo", "Aurelio", "Baltasar", "Bastián", "Beltrán", "Bernardo",
    "Berto", "Blas", "Bonifacio", "Borja", "Brayan", "Caín", "Calixto", "Casimiro", "Cayetano", "Celestino",
    "Ciro", "Claudio", "Clemente", "Dante", "Darío", "Demetrio", "Dionisio", "Domingo", "Donato", "Doroteo",
    "Edgar", "Edmundo", "Eliseo", "Eloy", "Emanuel", "Epifanio", "Erick", "Estanislao", "Ezequiel", "Félix",
    "Federico", "Flavio", "Florencio", "Fortunato", "Froilán", "Gaspar", "Genaro", "Genaro", "Gervasio", "Gilberto",
    "Godofredo", "Gregorio", "Gumersindo", "Heriberto", "Hermenegildo", "Honorio", "Horacio", "Humberto", "Inocencio", "Isandro",
    "Isauro", "Isidoro", "Jacinto", "Jacobo", "Jairo", "Jenaro", "Jeremías", "Jerónimo", "Jesualdo", "Joan",
    "Joel", "Jonatan", "Jordán", "Josué", "Juan Manuel", "Justino", "Lázaro", "Leocadio", "Leonel", "Lisandro",
    "Lorenzo", "Lucas", "Lucio", "Ludovico", "Luis Ángel", "Manolo", "Mariano", "Mario Alberto", "Martirio", "Maurilio",
    "Melchor", "Moisés", "Neftalí", "Nelson", "Néstor", "Norberto", "Octavio", "Odilón", "Olegario", "Omar",
    "Onésimo", "Orlando", "Osvaldo", "Otón", "Pánfilo", "Pascual", "Patricio", "Paulino", "Pío", "Próspero",
    "Ramón", "Reinaldo", "Renato", "Reyes", "Rito", "Roque", "Rosendo", "Rubí", "Rufo", "Sabino",
    "Salomón", "Sancho", "Sansón", "Saúl", "Severo", "Silvano", "Silverio", "Silvio", "Sixto", "Teodoro",
    "Timoteo", "Tirso", "Tobías", "Toribio", "Tristán", "Tulio", "Ubaldo", "Uberto", "Urbano", "Valerio",
    "Venancio", "Ventura", "Vicente", "Victoriano", "Victorio", "Vidal", "Vito", "Waldo", "Wilfredo", "Xavier",
    "Yago", "Yeray", "Yohan", "Yonatan", "Yordi", "Zacarías", "Zaid", "Zósimo", "Ángel", "Arón",
    "Azael", "Bladimir", "Ciro", "Cruz", "Darwin", "Eder", "Edwin", "Froilán", "Gael", "Homero",
    "Ian", "Isaías", "Jafet", "Joab", "Josías", "Kaled", "Lázaro", "Mauro", "Nazario", "Orencio",
    "Pablo Andrés", "Raimundo", "Samuel David", "Teobaldo", "Uziel", "Valentín José", "Wilmer", "Yahir", "Zaidel", "Elian."
];

export const girlNames = [
    "Abril", "Adela", "Adriana", "Agustina", "Aída", "Alba", "Alejandra", "Alicia", "Alma", "Amalia",
    "Amanda", "Amparo", "Ana", "Andrea", "Angela", "Anita", "Antonia", "Ariadna", "Ariana", "Aurora",
    "Beatriz", "Belén", "Bianca", "Blanca", "Brenda", "Camila", "Candela", "Carla", "Carmen", "Carolina",
    "Catalina", "Cecilia", "Celeste", "Clara", "Claudia", "Concepción", "Consuelo", "Cristina", "Daniela", "Diana",
    "Dolores", "Elena", "Elisa", "Emilia", "Esperanza", "Estela", "Esther", "Eva", "Fabiola", "Fatima",
    "", "Francisca", "Gabriela", "Gloria", "Graciela", "Guadalupe", "Helena", "Inés", "Irene", "Isabel",
    "Isidora", "Jacinta", "Jimena", "Josefina", "Juana", "Julia", "Juliana", "Karen", "Karina", "Laura",
    "Leticia", "Liliana", "Lorena", "Lucía", "Luisa", "Luna", "Magdalena", "Manuela", "Marcela", "María",
    "Mariana", "Marina", "Marta", "Martina", "Matilde", "Mercedes", "Micaela", "Milagros", "Mónica", "Natalia",
    "Noelia", "Norma", "Olga", "Paloma", "Patricia", "Paula", "Paz", "Pilar", "Raquel", "Rebeca",
    "Rocío", "Rosa", "Rosario", "Sandra", "Sara", "Silvia", "Sofía", "Soledad", "Susana", "Tatiana",
    "Teresa", "Valentina", "Valeria", "Vanesa", "Verónica", "Victoria", "Virginia", "Viviana", "Yolanda", "Zaira",
    "Zulema", "Aitana", "Alondra", "Amada", "Anabel", "Anastasia", "Ángela", "Araceli", "Azucena", "Bárbara",
    "Begoña", "Brígida", "Caridad", "Carmela", "Cecilia", "Celina", "Clotilde", "Concha", "Coral", "Corina",
    "Cristal", "Dafne", "Débora", "Delia", "Delfina", "Desirée", "Digna", "Dina", "Dominga", "Dorotea",
    "Edith", "Efigenia", "Elda", "Elvira", "Emiliana", "Erika", "Esmeralda", "Estefanía", "Eugenia", "Eulalia",
    "Eusebia", "Evelyn", "Fátima", "Felisa", "Filomena", "Flavia", "Flor", "Florencia", "Fortunata", "Francisca",
    "Fulgencia", "Genoveva", "Geraldina", "Gertrudis", "Gilda", "Gimena", "Gregoria", "Guillermina", "Herminia", "Hilda",
    "Hipólita", "Hortensia", "Ignacia", "Iliana", "Imelda", "Inmaculada", "Irene", "Irma", "Isabel", "Isidora",
    "Jacinta", "Jesusa", "Joaquina", "Josefa", "Josefina", "Juana", "Juliana", "Justina", "Lara", "Laura",
    "Leonor", "Leticia", "Lidia", "Lilia", "Liliana", "Lina", "Lorena", "Lucía", "Lucila", "Lucrecia",
    "Luisa", "Luz", "Magdalena", "Manuela", "Marcela", "Margarita", "María", "Mariana", "Maricela", "Mariela",
    "Marina", "Marisol", "Marta", "Martina", "Matilde", "Melania", "Mercedes", "Micaela", "Milagros", "Mireya",
    "Mónica", "Nadia", "Natividad", "Nélida", "Nerea", "Nieves", "Noelia", "Norma", "Nuria", "Obdulia",
    "Ofelia", "Olga", "Oliva", "Paloma", "Patricia", "Paula", "Paz", "Pilar", "Priscila", "Purificación",
    "Raquel", "Rebeca", "Regina", "Remedios", "Rita", "Roberta", "Rocío", "Romina", "Rosa", "Rosalía",
    "Rosario", "Roxana", "Rufina", "Salomé", "Sandra", "Sara", "Selena", "Silvia", "Simona", "Sofía",
    "Soledad", "Sonia", "Susana", "Tamara", "Tatiana", "Teodora", "Teresa", "Trinidad", "Úrsula", "Valentina",
    "Valeria", "Vanesa", "Verónica", "Vicenta", "Victoria", "Virginia", "Viviana", "Yolanda", "Zaira", "Zulema",
    "Abigail", "Adelaida", "Agustina", "Aída", "Alba", "Alejandra", "Alicia", "Alma", "Amalia", "Amanda",
    "Amparo", "Ana", "Andrea", "Ángela", "Anita", "Antonia", "Ariadna", "Ariana", "Aurora", "Beatriz",
    "Belén", "Bianca", "Blanca", "Brenda", "Camila", "Candela", "Carla", "Carmen", "Carolina", "Catalina",
    "Cecilia", "Celeste", "Clara", "Claudia", "Concepción", "Consuelo", "Cristina", "Daniela", "Diana", "Dolores",
    "Elena", "Elisa", "Emilia", "Esperanza", "Estela", "Esther", "Eva", "Fabiola", "Fatima", "",
    "Francisca", "Gabriela", "Gloria", "Graciela", "Guadalupe", "Helena", "Inés", "Irene", "Isabel", "Isidora",
    "Jacinta", "Jimena", "Josefina", "Juana", "Julia", "Juliana", "Karen", "Karina", "Laura", "Leticia",
    "Liliana", "Lorena", "Lucía", "Luisa", "Luna", "Magdalena", "Manuela", "Marcela", "María", "Mariana",
    "Marina", "Marta", "Martina", "Matilde", "Mercedes", "Micaela", "Milagros", "Mónica", "Natalia", "Noelia",
    "Norma", "Olga", "Paloma", "Patricia", "Paula", "Paz", "Pilar", "Raquel", "Rebeca", "Rocío",
    "Rosa", "Rosario", "Sandra", "Sara", "Silvia", "Sofía", "Soledad", "Susana", "Tatiana", "Teresa",
    "Valentina", "Valeria", "Vanesa", "Verónica", "Victoria", "Virginia", "Viviana", "Yolanda", "Zaira", "Zulema",
    "Aitana", "Alondra", "Amada", "Anabel", "Anastasia", "Ángela", "Araceli", "Azucena", "Bárbara", "Begoña",
    "Brígida", "Caridad", "Carmela", "Cecilia", "Celina", "Clotilde", "Concha", "Coral", "Corina", "Cristal",
    "Dafne", "Débora", "Delia", "Delfina", "Desirée", "Digna", "Dina", "Dominga", "Dorotea", "Edith",
    "Efigenia", "Elda", "Elvira", "Emiliana", "Erika", "Esmeralda", "Estefanía", "Eugenia", "Eulalia", "Eusebia",
    "Evelyn", "Fátima", "Felisa", "Filomena", "Flavia", "Flor", "Florencia", "Fortunata", "Francisca", "Fulgencia",
    "Genoveva", "Geraldina", "Gertrudis", "Gilda", "Gimena", "Gregoria", "Guillermina", "Herminia", "Hilda", "Hipólita",
    "Hortensia", "Ignacia", "Iliana", "Imelda", "Inmaculada", "Irene", "Irma", "Isabel", "Isidora", "Jacinta",
    "Jesusa", "Joaquina", "Josefa", "Josefina", "Juana", "Juliana", "Justina", "Lara", "Laura", "Leonor",
    "Leticia", "Lidia", "Lilia", "Liliana", "Lina", "Lorena", "Lucía", "Lucila", "Lucrecia", "Luisa",
    "Luz", "Magdalena", "Manuela", "Marcela", "Margarita", "María", "Mariana", "Maricela", "Mariela", "Marina",
    "Marisol", "Marta", "Martina", "Matilde", "Melania", "Mercedes", "Micaela", "Milagros", "Mireya", "Mónica",
    "Nadia", "Natividad", "Nélida", "Nerea", "Nieves", "Noelia", "Norma."
]   